---
dependencies:
- role: ansiblebit.oracle-java
  oracle_java_use_defaults: no
  oracle_java_apt_repository: 'deb http://ppa.launchpad.net/webupd8team/java/ubuntu bionic main'
  oracle_java_apt_repository_key: 'EA8CACC073C3DB2A'
  oracle_java_cache_valid_time: 3600
  oracle_java_deb_package: 'oracle-java8-installer'
  oracle_java_debconf_package_default: 'oracle-java8-set-default'
  oracle_java_home: "/usr/lib/jvm/java-8-oracle"
  oracle_java_set_as_default: yes
  oracle_java_state: latest
