---
- debug: msg="ethereum_data_directory = {{ ethereum_data_directory }}"

- apt_repository:
    repo: ppa:ethereum/ethereum
    state: present

- name: ensure apt cache is up to date
  apt: update_cache=yes

- name: ensure packages are installed
  apt: name={{item}}
  with_items:
    - ethereum
    - solc
    - pwgen

- name: "Ensures {{ ethereum_data_directory }} dir exists"
  file:
    path: "{{ ethereum_data_directory }}"
    state: directory
    
- name: Install geth service
  template:
    src: "geth-{{ type }}.service.j2"
    dest: /etc/systemd/system/geth.service

- name: Start geth service
  systemd:
    state: restarted
    name: geth
    daemon_reload: yes
    enabled: yes


- name: Ensure /opt/ethereum/ directory exists
  file:
    path: /opt/ethereum
    recurse: yes
    state: directory

- name: Ensure local facts directory exists
  file:
    path: /etc/ansible/facts.d
    recurse: yes
    state: directory

- name: Install ethereum wallet generation script
  template:
    src: generate-address.sh.j2
    dest: /opt/ethereum/generate-address.sh
    mode: 0755

- name: Generate ethereum wallet
  shell: /opt/ethereum/generate-address.sh
  when: ansible_local.ethereum is not defined

- name: Reload ansible_local facts
  setup:
    filter: ansible_local
  when: ansible_local.ethereum is not defined

- name: Generated ethereum wallet
  debug:
    msg: "address={{ ansible_local.ethereum.address }}, passphrase={{ ansible_local.ethereum.passphrase }}"

