---
- debug: msg="bitcoind_data_directory = {{ bitcoind_data_directory }}"

- apt_repository:
    repo: ppa:bitcoin/bitcoin
    state: present

- name: ensure apt cache is up to date
  apt: update_cache=yes

- name: ensure packages are installed
  apt: name={{item}}
  with_items:
    - bitcoind

- name: "Ensures {{ bitcoind_data_directory }} dir exists"
  file:
    path: "{{ bitcoind_data_directory }}"
    state: directory

- name: "Install {{ bitcoind_data_directory }}/bitcoin.conf"
  template:
    src: bitcoin.conf.j2
    dest: "{{ bitcoind_data_directory }}/bitcoin.conf"

- name: Install bitcoind service
  template:
    src: bitcoind.service.j2
    dest: /etc/systemd/system/bitcoind.service

- name: Start bitcoind service
  systemd:
    state: restarted
    name: bitcoind
    daemon_reload: yes
    enabled: yes
