---
- hosts: aces-node-1
  become: true
  vars:
     database_name: aces_marketplace
     database_user: aces_marketplace_user
     database_password: change_me
  roles:
    - role: aces-common
    - role: aces-marketplace
      database_name: database_name
      database_user: database_user
      database_password: database_password
