---
- import_playbook: setup-playbook.yml
- hosts: aces-node-1
  become: true
  roles:
    - role: aces-common
    - role: aces-marketplace
      database_name: database_name
      database_user: database_user
      database_password: database_password
