--- 
- name: "Install nginx local proxy for {{ app_service_name }}"
  import_role:
    name: nginx-proxy-local
  vars:
    domain_name: "{{ domain_name }}"
    app_port: "{{ app_port }}"
  when: use_letsencrypt == false
 
- name: "Install nginx letsencrypt proxy for {{ app_service_name }}"
  import_role:
    name: nginx-proxy-letsencrypt
  vars:
    domain_name: "{{ domain_name }}"
    letsencrypt_email: "{{ letsencrypt_email }}"
    app_port: "{{ app_port }}"
  when: use_letsencrypt == true
