---
app_service_name: aces-marketplace
app_password: change_me
app_port: 8081
mail_host: smtp.mailgun.org
mail_port: 465
mail_user: change_me
mail_password: change_me
fromName: "ACES Marketplace"
fromEmailAddress: aces-marketplace@example.com
base_url: https://aces-marketplace.example.com
recaptcha_secret: change_me
recaptcha_site_key: change_me
letsencrypt_email: aces-marketplace@example.com
use_letsencrypt: false
database_host: localhost
database_port: 5432
database_name: aces_marketplace
database_user: aces_marketplace_user
database_password: change_me
use_local_database: true
domain_name: aces-marketplace.example.com