---
- apt_repository:
    repo: ppa:bitcoin/bitcoin
    state: present

- name: ensure apt cache is up to date
  apt: update_cache=yes

- name: ensure packages are installed
  apt: name={{item}}
  with_items:
    - bitcoind

- name: "Ensures {{ bitcoind_data_directory }} dir exists"
  file:
    path: "{{ bitcoind_data_directory }}"
    state: directory

- name: "Install {{ bitcoind_data_directory }}/bitcoin.conf"
  template:
    src: bitcoin.conf.j2
    dest: "{{ bitcoind_data_directory }}/bitcoin.conf"

- name: Install bitcoind service
  template:
    src: bitcoind.service.j2
    dest: /etc/systemd/system/bitcoind.service

- name: Start bitcoind service
  systemd:
    state: restarted
    name: bitcoind
    daemon_reload: yes
    enabled: yes

- name: Ensure /opt/bitcoin/ directory exists
  file:
    path: /opt/bitcoin
    recurse: yes
    state: directory

- name: Ensure local facts directory exists
  file:
    path: /etc/ansible/facts.d
    recurse: yes
    state: directory
    
- name: Install bitcoin wallet generation script
  template:
    src: generate-address.sh.j2
    dest: /opt/bitcoin/generate-address.sh
    mode: 0755

- name: Generate bitcoin wallet
  shell: /opt/bitcoin/generate-address.sh
  when: ansible_local.bitcoin is not defined

- name: Reload ansible_local facts
  setup:
    filter: ansible_local
  when: ansible_local.bitcoin is not defined

- name: Generated bitcoin wallet address
  debug:
    msg: "{{ ansible_local.bitcoin.address }}"
