---
- name: "Ensures /etc/opt/{{ app_service_name }}/ dir exists"
  file:
    path: "/etc/opt/{{ app_service_name }}"
    state: directory
    
- name: "Ensures /opt/{{ app_service_name }}/bin dir exists"
  file:
    path: "/opt/{{ app_service_name }}/bin"
    state: directory

- name: "Download {{ jar_name }} application jar"
  get_url:
    url: "https://arkaces.com/aces-packages/{{ jar_name }}"
    dest: "/opt/{{ app_service_name }}/bin/{{ app_service_name }}.jar"

- name: "Install {{ app_service_name }} service"
  template:
    src: application.service.j2
    dest: "/etc/systemd/system/{{ app_service_name }}.service"

- name: "Start {{ app_service_name }} service"
  systemd:
    state: restarted
    name: "{{ app_service_name }}"
    daemon_reload: yes
    enabled: yes

- name: "Wait for {{ app_service_name }} application to start up"
  wait_for:
    port: "{{ app_port }}"
    delay: 1
    timeout: 600

- name: "Expose {{ app_service_name }} port"
  ufw:
    rule: allow
    port: "{{ app_port }}"
    proto: tcp
  when: expose_port == true

